spring:
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:mysql://10.20.4.51:3306/flyway_test1?useUnicode=true&characterEncoding=utf8&useSSL=false&verifyServerCertificate=false&allowPublicKeyRetrieval=true
    username: root
    password: YY5VV5
    driver-class-name: com.mysql.cj.jdbc.Driver


flyway:
  #是否开启
  enabled: true
  #迁移脚本的位置，默认db/migration
  #locations: classpath:/db/migration
  #是否允许无序的迁移
  out-of-order: false
  #当初始化好连接时要执行的SQL
  #init-sqls:
  #使用的元数据表名-->版本记录
  table: schema_version
